const fields = {
    'package':'Package',
    'type': 'type',
    'name': 'name',
    'description': 'description',
    'version': 'version',
    'status': 'status',
    'Required': 'Required',
    'Property': 'Property',
    'isID': 'isID',
    'status': 'status',
    'pattern': 'pattern',
    'DataType': 'DataType',
    'cardinality': 'cardinality',
    'enum': 'enum',
    'Relationship': 'Relationship',
    'Operation': 'Operation',
    'Parameter': 'Parameter',
    'source': 'source',
    'target': 'target',
    'association': 'association',
    'class': 'class',
    'from': 'from',
    'to': 'to',
    'Entity' : 'Entity',
    'Event' : 'Event',
    'interfaceRealization' : 'interfaceRealization',
    'generalization' : 'generalization',
    'associationClassLink' : 'associationClassLink',
    'enum' : 'enum',
    'aggregation':'aggregation',
    'composition':'composition',
    'interface':'interface',
};
module.exports = fields;