const fields = {
    autoResize: 'autoResize',
    fillColor: 'fillColor',
    fontColor: 'fontColor',
    lineColor: 'lineColor',
    containerChangeable: 'containerChangeable',
    containerExtending: 'containerExtending',
    enabled: 'enabled',
    minHeight: 'minHeight',
    minWidth: 'minWidth',
    movable: 'movable',
    parentStyle: 'parentStyle',
    selectZIndex: 'selectZIndex',
    selectable: 'selectable',
    selected: 'selected',
    showMultiplicity: 'showMultiplicity',
    showNamespace: 'showNamespace',
    showOperationSignature: 'showOperationSignature',
    showProperty: 'showProperty',
    showShadow: 'showShadow',
    showType: 'showType',
    showVisibility: 'showVisibility',
    sizable: 'sizable',
    stereotypeDisplay: 'stereotypeDisplay',
    suppressAttributes: 'suppressAttributes',
    suppressLiterals: 'suppressLiterals',
    suppressOperations: 'suppressOperations',
    suppressReceptions: 'suppressReceptions',
    visible: 'visible',
    wordWrap: 'wordWrap',
    zIndex: 'zIndex',

};
module.exports = fields;